"""added Session table

Revision ID: c49d5f05b361
Revises: d1d2830a3a72
Create Date: 2018-08-24 20:53:52.055717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49d5f05b361'
down_revision = 'd1d2830a3a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('practice_time', sa.DateTime(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_date'), 'session', ['date'], unique=False)
    op.create_index(op.f('ix_session_practice_time'), 'session', ['practice_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_practice_time'), table_name='session')
    op.drop_index(op.f('ix_session_date'), table_name='session')
    op.drop_table('session')
    # ### end Alembic commands ###
